version: '2'
services:
  webapp:
    image: datamill/datamill-webapp:v1.1.0
    build:
      context: ./
      dockerfile: Dockerfile-Datamill-Webapp
    network_mode: host
    restart: always
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
    - mongodb
    - redis
    links:
      - mongodb
      - redis
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB_NAME: datamillsever
      REDIS_HOST: redis
      REDIS_PORT: 6379
  mongodb:
    image: mongo
    network_mode: host
    restart: always
    volumes:
      - /data:/data/db
    expose:
      - 27017
  redis:
   image: redis
   network_mode: host
   restart: always
   expose:
     - 6379
