FROM mhart/alpine-node:6.3.0
RUN mkdir -p /usr/src/app
ADD . /usr/src/app
COPY package.json /usr/src/app
WORKDIR /usr/src/app
RUN npm install
COPY . /usr/src/app
WORKDIR /usr/src/app
CMD ["npm","start"]